# ZSH configuration file
# This is the zlogout file sourced directly by zsh
# Written by Martin Ebourne
#
# $Id: zlogout 792 2003-09-22 11:47:18Z martin $

ZFILE=zlogout
[[ -n $ZCONFIGDEBUG ]] && echo "Executing config file $ZFILE"

[[ -z $ZCONFIGDIR ]] && { print "ERROR: ZCONFIGDIR unset in $ZFILE" ; exit 1 }

# NB. We excecute the logout files in REVERSE order
config_if_present user/logout
config_if_present local/current/logout
config_if_present system/logout

[[ -n $ZCONFIGDEBUG ]] && echo "Finished config file $ZFILE"
unset ZFILE
