# ZSH configuration file
# This is the zprofile file sourced directly by zsh
# Written by Martin Ebourne
#
# $Id: zprofile,v 1.5 2001/05/23 13:21:50 mebourne Exp $

ZFILE=zprofile
[[ -n $ZCONFIGDEBUG ]] && echo "Executing config file $ZFILE"

_init_zprofile() {
  [[ -z $ZCONFIGDIR ]] && { print "ERROR: ZCONFIGDIR unset in $ZFILE" ; exit 1 }

  config_if_present system/login
  config_if_present local/current/login
  config_if_present user/login
}
_init_zprofile
unfunction _init_zprofile

[[ -n $ZCONFIGDEBUG ]] && echo "Finished config file $ZFILE"
unset ZFILE
